baseURL = "https://charrrrls.github.io/"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "charrrrlsçš„æŠ€æœ¯åšå®¢"

# theme as git submodule
theme = "PaperMod"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[services]
# Enable Disqus.Disqus.Shortname
  [services.disqus]
    #shortname = 'your-disqus-shortname'
# Google Analytics
  [services.googleAnalytics]
    #ID = 'G-MEASUREMENT_ID'

[params]
env = "production"
title = "charrrrlsçš„æŠ€æœ¯åšå®¢"
description = "çƒ­çˆ±æŠ€æœ¯çš„å¼€å‘è€…ï¼Œè®°å½•å­¦ä¹ è¿‡ç¨‹ä¸­çš„ç‚¹ç‚¹æ»´æ»´"
keywords = ["æŠ€æœ¯åšå®¢", "ç¼–ç¨‹", "å¼€å‘", "å­¦ä¹ ç¬”è®°", "charrrrls"]
author = "charrrrls"
# author = ["Me", "You"] # multiple authors
images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "2006å¹´01æœˆ02æ—¥"
defaultTheme = "auto" # dark, light
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon = "<link / abs url>"
    favicon16x16 = "<link / abs url>"
    favicon32x32 = "<link / abs url>"
    apple_touch_icon = "<link / abs url>"
    safari_pinned_tab = "<link / abs url>"

label:
    text = "é¦–é¡µ"
    icon = /apple-touch-icon.png
    iconHeight = 35

# profile-mode
profileMode:
    enabled = false # needs to be explicitly set
    title = ExampleSite
    subtitle = "This is subtitle"
    imageUrl = "<img location>"
    imageWidth = 120
    imageHeight = 120
    imageTitle = my image
    buttons:
        - name = Posts
          url = posts
        - name = Tags
          url = tags

# home-info mode
homeInfoParams:
    Title = "Hi there ğŸ‘‹"
    Content = "Welcome to my blog"

socialIcons:
    - name = github
      url = "https://github.com/charrrrls"
    - name = email
      url = "mailto:164527250+charrrrls@users.noreply.github.com"
    - name = rss
      url = "/index.xml"

analytics:
    google:
        SiteVerificationTag = "XYZabc"
    bing:
        SiteVerificationTag = "XYZabc"
    yandex:
        SiteVerificationTag = "XYZabc"

cover:
    hidden = true # hide everywhere but not in structured data
    hiddenInList = true # hide on list pages and home
    hiddenInSingle = true # hide on single page

editPost:
    URL = "https://github.com/charrrrls/blog-source/tree/main/content"
    Text = "Suggest Changes" # edit text
    appendFilePath = true # to append file path to Edit link

# for search
# https://fusejs.io/api/options.html
fuseOpts:
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]
